# Generated by Django 3.2 on 2025-04-16 02:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0003_alter_fooditem_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fooditem',
            name='image',
            field=models.ImageField(default=None, upload_to='foodimages'),
        ),
    ]
